name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print greeting
        run: echo "hello Nederland !!"
      - name: print goodby
        run: |
          echo "Issu is fixed !!"
          echo "Weldone !!"
